Fix part controller demo
ARISE-Initiative/robosuite pull request #546
Opened 2024-11-04 07:49 UTC by youliangtan

### Summary

This addresses both of these issues related to the controller.
 - https://github.com/ARISE-Initiative/robosuite/issues/534
 - https://github.com/ARISE-Initiative/robosuite/issues/532

 - This PR added the previous v1.4 controller configs, so users can still initiate only a single controller (as opposed to `composite), via the `load_part_controller_config()` method.
 - Also there are some inconsistency of using `body_parts` in the internal implementation of handling `controller_configs`, I kept it consistent with the `body_parts_controller_configs` key. Still, I not a fan of dynamically changing the config dict in the internal method.
 - fixes the  `demo_control.py` and `tune_joints.py` scripts.

### What to Run

```sh
 python python robosuite/demos/demo_control.py
```

```sh
 python robosuite/scripts/tune_joints.py 
```

Also all test cases passed.

2024-11-05 20:33 UTC, Abhiram824 commented on robosuite/controllers/composite/composite_controller_factory.py
Is this change needed? Preferably we could go without this change and just update the entrypoint scripts instead.

2024-11-05 20:35 UTC, Abhiram824 commented on robosuite/demos/demo_control.py
Ideally, instead of constructing the composite controller config from scratch, we could load the default composite controller for each robot and override the arm controller based on the input to this script

2024-11-05 20:39 UTC, Abhiram824 commented on robosuite/controllers/config/parts/default_ur5e.json
Do we need this directory: robosuite/controllers/config/ ?

2024-11-05 20:42 UTC, Abhiram824 commented on robosuite/controllers/config/parts/default_jaco (copy).json
assuming this is not needed?

2024-11-05 20:42 UTC, Abhiram824 requested changes
Looks good overall. I think theres some extraneous code in the commit that can be removed though.

2024-11-06 02:07 UTC, kevin-thankyou-lin commented on robosuite/controllers/composite/composite_controller_factory.py
Do you mean to update `body_parts_controller_configs` to `body_parts` in the `json` files?
I think this more of a style question, but I agree w/ keeping things consistent

2024-11-06 02:15 UTC, kevin-thankyou-lin requested changes

2024-11-06 02:15 UTC, kevin-thankyou-lin commented on robosuite/controllers/config/parts/default_baxter.json
I think we can remove the  `../config/parts/` directory, since we already have robot defaults in the `robosuite/controllers/config/robots/` folder

2024-11-06 02:15 UTC, kevin-thankyou-lin commented on robosuite/controllers/config/parts/default_ur5e.json
are you referring to `robosuite/controllers/config/parts/`?

2024-11-06 02:15 UTC, kevin-thankyou-lin commented on robosuite/demos/demo_control.py
agreed

2024-11-06 02:15 UTC, kevin-thankyou-lin commented on robosuite/demos/demo_control.py
> +    part_controller_config = suite.load_part_controller_config(default_controller=controller_name)
Could we prompt the user for the actual body part? E.g. humanoid might have multiple body parts and I suspect this script may fail for e.g. GR1FixedLowerBody

2024-11-06 21:19 UTC, kevin-thankyou-lin approved these changes

2024-11-06 22:58 UTC, Abhiram824 commented on robosuite/utils/input_utils.py
This function is no longer needed since `choose_controller(part_controllers=True)` gives the same behavior

2024-11-06 23:00 UTC, Abhiram824 commented on robosuite/controllers/composite/composite_controller_factory.py
do we need to change the key from `body_parts` to `body_parts_controller_config` I think if don't do this. This PR will have less changes

2024-11-07 01:21 UTC, kevin-thankyou-lin commented on robosuite/utils/input_utils.py
removed

2024-11-07 01:22 UTC, kevin-thankyou-lin approved these changes

2024-11-07 01:22 UTC, kevin-thankyou-lin commented on robosuite/controllers/composite/composite_controller_factory.py
I think updating is fine for consistency?

2024-11-07 01:40 UTC, Abhiram824 approved these changes

2024-11-07 01:44 UTC, merged

2024-11-07 01:57 UTC, kevin-thankyou-lin commented
Resolves issue #534