Adding render modalities
ARISE-Initiative/robosuite pull request #596
Opened 2024-12-18 15:13 UTC by abhihjoshi

Adding normals and semantic segmentation render modalities.

2024-12-18 23:18 UTC, kevin-thankyou-lin requested changes

2024-12-18 23:18 UTC, kevin-thankyou-lin commented on robosuite/scripts/render_dataset_with_omniverse.py
> +# adding rendering types
Thanks! Could we also include instructions for how to install isaac successfully e.g. in this file?

2025-01-02 22:59 UTC, snasiriany commented
Are we ready to merge? @kevin-thankyou-lin

2025-01-02 23:18 UTC, kevin-thankyou-lin approved these changes

2025-01-02 23:18 UTC, kevin-thankyou-lin commented
Seems okay to me, approved @snasiriany

2025-01-08 19:31 UTC, merged